CREATE TABLE `ActivityLog` (`id` integer, `userId` integer, `action` varchar(255), `entityId` integer, `recordId` integer, `createdAt` datetime not null default CURRENT_TIMESTAMP, foreign key(`userId`) references `User`(`id`), foreign key(`entityId`) references `Entity`(`id`), foreign key(`recordId`) references `Record`(`id`), primary key (`id`))
CREATE TABLE `ApiToken` (`id` integer, `name` varchar(255), `tokenHash` varchar(255), `createdAt` datetime not null default CURRENT_TIMESTAMP, `expiresAt` datetime, primary key (`id`))
CREATE TABLE `Entity` (`id` integer, `name` varchar(255), `slug` varchar(255), `tableName` varchar(255), `createdAt` datetime not null default CURRENT_TIMESTAMP, primary key (`id`))
CREATE TABLE `Field` (`id` integer, `entityId` integer, `name` varchar(255), `slug` varchar(255), `type` varchar(255), `required` boolean, `uniqueField` boolean, `defaultValue` varchar(255), `configJson` varchar(255), `position` integer, foreign key(`entityId`) references `Entity`(`id`), primary key (`id`))
CREATE TABLE `Media` (`id` integer, `filename` varchar(255), `mimeType` varchar(255), `size` integer, `path` varchar(255), `altText` varchar(255), `uploadedById` integer, `createdAt` datetime not null default CURRENT_TIMESTAMP, foreign key(`uploadedById`) references `User`(`id`), primary key (`id`))
CREATE TABLE `Permission` (`id` integer, `roleId` integer, `entityId` integer, `canCreate` boolean, `canRead` boolean, `canUpdate` boolean, `canDelete` boolean, foreign key(`roleId`) references `Role`(`id`), foreign key(`entityId`) references `Entity`(`id`), primary key (`id`))
CREATE TABLE `Record` (`id` integer, `entityId` integer, `dataJson` text, `createdById` integer, `updatedById` integer, `createdAt` datetime not null default CURRENT_TIMESTAMP, `updatedAt` datetime not null default CURRENT_TIMESTAMP, `status` varchar(255), foreign key(`entityId`) references `Entity`(`id`), foreign key(`createdById`) references `User`(`id`), foreign key(`updatedById`) references `User`(`id`), primary key (`id`))
CREATE TABLE `RecordTag` (`recordId` integer, `tagId` integer, foreign key(`recordId`) references `Record`(`id`), foreign key(`tagId`) references `Tag`(`id`), primary key (`recordId`, `tagId`))
CREATE TABLE `RecordVersion` (`id` integer, `recordId` integer, `entityId` integer, `dataJson` text, `createdAt` datetime not null default CURRENT_TIMESTAMP, `createdById` integer, foreign key(`recordId`) references `Record`(`id`), foreign key(`entityId`) references `Entity`(`id`), foreign key(`createdById`) references `User`(`id`), primary key (`id`))
CREATE TABLE `Relation` (`id` integer, `fieldId` integer, `relationType` varchar(255), `targetEntityId` integer, `pivotTable` varchar(255), foreign key(`fieldId`) references `Field`(`id`), foreign key(`targetEntityId`) references `Entity`(`id`), primary key (`id`))
CREATE TABLE `Role` (`id` integer, `name` varchar(255), `description` varchar(255), primary key (`id`))
CREATE TABLE `Tag` (`id` integer, `name` varchar(255), `slug` varchar(255), primary key (`id`))
CREATE TABLE `User` (`id` integer, `email` varchar(255), `passwordHash` varchar(255), `name` varchar(255), `roleId` integer, `createdAt` datetime not null default CURRENT_TIMESTAMP, `updatedAt` datetime not null default CURRENT_TIMESTAMP, foreign key(`roleId`) references `Role`(`id`), primary key (`id`))
CREATE TABLE `WebHook` (`id` integer, `event` varchar(255), `url` varchar(255), `secret` varchar(255), primary key (`id`))

CREATE UNIQUE INDEX `entity_slug_unique` on `Entity` (`slug`)
CREATE INDEX `field_entityid_index` on `Field` (`entityId`)
CREATE INDEX `record_entityid_index` on `Record` (`entityId`)
CREATE UNIQUE INDEX `tag_slug_unique` on `Tag` (`slug`)
CREATE UNIQUE INDEX `user_email_unique` on `User` (`email`)